### PR TITLE
Fixes https://github.com/electricjs/electric/issues/62

### PR DESCRIPTION
**Pull request by ygorcosta**
Hey guys, about this issue... idk if it's the best solution but it fixes the problem.
I realized that Javascript had not yet been fully loaded when ReadingProgress is created, so... I did this.

### CODE REVIEW

**Comment by robframpton** [comment]
Hey @ygorcosta,

Can you change it to an event listener for the `load` event instead?

**Comment by zenorocha** [comment]
@ygorcosta can you confirm that this works not only on the first load, but also when you start navigating?

**Comment by zenorocha** [comment]
Besides that, have you tried `DOMContentLoaded` event?

**Comment by ygorcosta** [comment]
yeah, it's not working well.
I'll work on another solution for this problem

**Pull request closed without merging**
